In [6]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
train = pd.read_csv(Path("/home/legionlinux/miniconda3/envs/torchenv/__INIT__/Kaggle/birdclef-2026/data/raw/train.csv"))
taxonomy = pd.read_csv(Path("/home/legionlinux/miniconda3/envs/torchenv/__INIT__/Kaggle/birdclef-2026/data/raw/taxonomy.csv"))

In [7]:
taxonomy

,primary_label,inat_taxon_id,scientific_name,common_name,class_name
0,1161364,1161364,Guyalna cuta,Guyalna cuta,Insecta
1,116570,116570,Caiman yacare,Southern Spectacled Caiman,Reptilia
2,1176823,1176823,Leptodactylus luctator,Wrestler Frog,Amphibia
3,1491113,1491113,Adenomera guarani,Guaraní leaf-litter frog,Amphibia
4,1595929,1595929,Lysapsus limellum,Uruguay Harlequin Frog,Amphibia
...,...,...,...,...,...
229,yebela1,16714,Elaenia flavogaster,Yellow-bellied Elaenia,Aves
230,yecmac,73272,Primolius auricollis,Golden-collared Macaw,Aves
231,yecpar,19215,Brotogeris chiriri,Yellow-chevroned Parakeet,Aves
232,yehcar1,1432779,Daptrius chimachima,Yellow-headed Caracara,Aves
233,yeofly1,16567,Tolmomyias sulphurescens,Yellow-olive Flatbill,Aves

In [9]:
taxonomy[~taxonomy['primary_label'].isin(train['primary_label'])]

,primary_label,inat_taxon_id,scientific_name,common_name,class_name
3,1491113,1491113,Adenomera guarani,Guaraní leaf-litter frog,Amphibia
23,25073,25073,Chiasmocleis mehelyi,Chiasmocleis mehelyi,Amphibia
30,47158son01,47158,Insect son01,Insect sonotype01,Insecta
31,47158son02,47158,Insect son02,Insect sonotype02,Insecta
32,47158son03,47158,Insect son03,Insect sonotype03,Insecta
33,47158son04,47158,Insect son04,Insect sonotype04,Insecta
34,47158son05,47158,Insect son05,Insect sonotype05,Insecta
35,47158son06,47158,Insect son06,Insect sonotype06,Insecta
36,47158son07,47158,Insect son07,Insect sonotype07,Insecta
37,47158son08,47158,Insect son08,Insect sonotype08,Insecta
38,47158son09,47158,Insect son09,Insect sonotype09,Insecta
39,47158son10,47158,Insect son10,Insect sonotype10,Insecta
40,47158son11,47158,Insect son11,Insect sonotype11,Insecta
41,47158son12,47158,Insect son12,Insect sonotype12,Insecta
42,47158son13,47158,Insect son13,Insect sonotype13,Insecta
43,47158son14,47158,Insect son14,Insect sonotype14,Insecta
44,47158son15,47158,Insect son15,Insect sonotype15,Insecta
45,47158son16,47158,Insect son16,Insect sonotype16,Insecta
46,47158son17,47158,Insect son17,Insect sonotype17,Insecta
47,47158son18,47158,Insect son18,Insect sonotype18,Insecta
48,47158son19,47158,Insect son19,Insect sonotype19,Insecta
49,47158son20,47158,Insect son20,Insect sonotype20,Insecta
50,47158son21,47158,Insect son21,Insect sonotype21,Insecta
51,47158son22,47158,Insect son22,Insect sonotype22,Insecta
52,47158son23,47158,Insect son23,Insect sonotype23,Insecta
53,47158son24,47158,Insect son24,Insect sonotype24,Insecta
54,47158son25,47158,Insect son25,Insect sonotype25,Insecta
57,517063,517063,Pithecopus azureus,Southern Orange-legged Leaf Frog,Amphibia